spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/javademo
    password: root
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
         global_quoted_identifiers: true
         dialect: org.hibernate.dialect.MySQL8Dialect
         format_sql: true
  sql:
    init:
      mode: never
